# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf23ab18b2a522cb8e5c2359f5a571f37ab67fa8cbba66a9f624f951c5b9116917dc645f8faa54a6ef05e034e4675a336ce30d1f1f0a1450daf2cb65ea24ed27

test:
  secret_key_base: ac361ad8a2333e0d422653e2ee7398e4710bcee38d5494d1761be88cc831be81c278fd13e91a0e144d6afd3aacf45b123ee2fd797f014781656500aa3364e50f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
